#!/bin/sh
#
# This file is part of the metrics repository. Copyright (C) 2013 and above Shogun <shogun@cowtech.it>.
# Licensed under the MIT license, which can be found at http://www.opensource.org/licenses/mit-license.php.
#

git clone https://github.com/ShogunPanda/metrics.git
ln -s metrics/metric_fu.rb .metrics
echo "metrics/" >> .gitignore
echo ".metrics" >> .gitignore
echo "tmp/metric_fu" >> .gitignore

